SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


CREATE TABLE IF NOT EXISTS `Car` (
`id_car` int(11) NOT NULL,
  `id_User` int(11) NOT NULL,
  `id_CarRegistry` int(11) NOT NULL,
  `Brand` text NOT NULL,
  `Model` text NOT NULL,
  `RegistrationNumber` text NOT NULL,
  `Insurer` text NOT NULL,
  `Others` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `Policy` (
`id_Policy` int(11) NOT NULL,
  `CreatedBy` int(11) NOT NULL,
  `id_registry` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `Registry` (
`id_Registry` int(11) NOT NULL,
  `id_User` int(11) NOT NULL,
  `Name` text NOT NULL,
  `CreateDate` date NOT NULL,
  `Type` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `Term` (
`id_Term` int(11) NOT NULL,
  `id_Car` int(11) NOT NULL,
  `Type` text NOT NULL,
  `DateFrom` date NOT NULL,
  `DateTo` int(11) NOT NULL,
  `Departments` text NOT NULL,
  `ReminderDate` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `Users` (
`id_User` int(11) NOT NULL,
  `Login` text NOT NULL,
  `Password` text NOT NULL,
  `Email` text NOT NULL,
  `Rights` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;


ALTER TABLE `Car`
 ADD PRIMARY KEY (`id_car`);

ALTER TABLE `Policy`
 ADD PRIMARY KEY (`id_Policy`);

ALTER TABLE `Registry`
 ADD PRIMARY KEY (`id_Registry`);

ALTER TABLE `Term`
 ADD PRIMARY KEY (`id_Term`);

ALTER TABLE `Users`
 ADD PRIMARY KEY (`id_User`);


ALTER TABLE `Car`
MODIFY `id_car` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `Policy`
MODIFY `id_Policy` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `Registry`
MODIFY `id_Registry` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `Term`
MODIFY `id_Term` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `Users`
MODIFY `id_User` int(11) NOT NULL AUTO_INCREMENT;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
